rootProject.name = "ReportMid"
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")


include(":lolResourceLib")
include(":app")
include(":appApi")
include(":appImpl")
include(":landingImpl")
include(":baseApi")
include(":baseImpl")
include(":utils")
include(":lol")
include(":lolServicesImpl")
include(":lolServicesApi")
include(":landingApi")
include(":resLib")
include(":theme")
include(":viewStateApi")
include(":viewStateImpl")
include(":leaguePositionApi")
include(":leaguePositionImpl")
include(":dataDragonApi")
include(":dataDragonImpl")
include(":dataDragonRoom")
include(":summonerApi")
include(":summonerImpl")
include(":summonerRoom")
include(":lolRoom")
include(":stateApi")
include(":stateImpl")
include(":stateRoom")
include(":kspProcessor")
include(":requestManagerApi")
include(":requestManagerImpl")
