rootProject.name = "Report Mid"

include(":lol-resource-lib")
include(":app")
include(":landing-impl")
include(":base")
include(":utils")
include(":lol")
include(":lol-services-impl")
include(":lol-services-api")
include(":app-api")
include(":landing-api")
include(":res-lib")
include(":theme")
include(":view-state-api")
include(":view-state-impl")
include(":league-position-api")
include(":league-position-impl")
include(":data-dragon-api")
include(":data-dragon-impl")
include(":data-dragon-room")
include(":summoner-api")
include(":summoner-impl")
include(":summoner-room")
include(":lol-room")
include(":state-api")
include(":state-impl")
include(":state-room")
